### ISSUE TITLE
Compilation Problem

### ISSUE THREAD

**Issue by altshuler** [Jaeyoung-Lim/mavros_controllers#61] opened 2019-03-17 20:25 UTC
Hello, 
I'm trying to compile the mavros_controllers and get compilation error:

Errors     << geometric_controller:check /home/evgeny/catkin_ws/logs/geometric_controller/build.check.017.log                
CMake Error at /home/evgeny/catkin_ws/devel/share/catkin_simple/cmake/catkin_simple-extras.cmake:38 (find_package):
  By not providing "Findeigen_catkin.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "eigen_catkin", but CMake did not find one.

  Could not find a package configuration file provided by "eigen_catkin" with
  any of the following names:

    eigen_catkinConfig.cmake
    eigen_catkin-config.cmake

  Add the installation prefix of "eigen_catkin" to CMAKE_PREFIX_PATH or set
  "eigen_catkin_DIR" to a directory containing one of the above files.  If
  "eigen_catkin" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:7 (catkin_simple)

make: *** [cmake_check_build_system] Error 1

What you think is a problem ?

Best regards
Evgeny

**Comment by Jaeyoung-Lim** [comment] 2019-03-17 20:33
This is a recently added dependency. Sorry for not updating the readme.
Try installing it through the `dependeincies.rosinstall` in the root of the repo
 ```
cd ~/catkin_ws
wstool merge -t src mavros_controllers/dependencies.rosinstall
wstool update -t src -j4
rosdep install --from-paths src --ignore-src -y --rosdistro kinetic
```
or you can simply clone it to the src directory as the following
```
git clone https://github.com/ethz-asl/eigen_catkin.git
```

**Comment by altshuler** [comment] 2019-03-18 15:17
Thank you very much.
This commands will update only mavros_controllers package or
all packages in workspace ? I have a packages that I don't want to update.

BR
Evgeny

**Comment by Jaeyoung-Lim** [comment] 2019-03-18 18:49
@altshuler If you are worried about dependencies, simply clone `eigen_catkin` into your workspace. That should be enough

**Comment by altshuler** [comment] 2019-03-19 06:19
Hello,
when I do   roslaunch geometric_controller trajectory_track_circle.launch    command.
I get this message: 
ERROR: cannot launch node of type [trajectory_publisher/trajectory_publisher]: can't locate node [trajectory_publisher] in package [trajectory_publisher]

The drone just takeoff and hovering in one place.

**Comment by Jaeyoung-Lim** [comment] 2019-03-19 06:47
Did you build the `trajectory publisher`?

**Comment by altshuler** [comment] 2019-03-19 07:21
Actually, no...
I didn't get that needed to build it separately.
Any other packages should be built separately ?

**Comment by Jaeyoung-Lim** [comment] 2019-03-19 07:35
As written in the instructions, if you build `mavros_controllers` it will build `trajectory_publisher` and `geometric_controller`

**Comment by altshuler** [comment] 2019-03-19 07:47
Ok, thanks.
Will test it today.

**Comment by Jaeyoung-Lim** [comment] 2019-03-24 19:23
@altshuler Any updates?

**Comment by altshuler** [comment] 2019-03-25 07:43
I'm compiled the packages, Running simulations ,
trying to understand the code.
I have 2 questions.
Ho I can disable running Gazebo every simulation ?
What launch file runs real flight (not simulation) ?

**Comment by Jaeyoung-Lim** [comment] 2019-03-25 09:33
@altshuler So does that mean the problem is solved?

On a real platform, you need to disable `sim_enable_` parameter and not launch `px4_sitl`.

Currently there is no launch file specifically for a real system. Do you need one?

**Comment by altshuler** [comment] 2019-03-25 09:46
Yes, the problem is solved.
I will try to fly on real drone.

Tanks

**Comment by Jaeyoung-Lim** [comment] 2019-04-08 15:05
@altshuler Have you tried flying?

**Comment by altshuler** [comment] 2019-04-08 18:42
Actually, yes. But the vehicle is not arming.
I disabled sim_enable_ parameter  and px4_sitl .
And I tried it before last updates that you added to the project.
Unfortunately I have some HW problems on my Intel Aero, so I will try it 
on next week. 

Can you explain in couple of words what dob_controller do ?

**Comment by Jaeyoung-Lim** [comment] 2019-04-08 20:06
Cool. Hope it works :smile: 

A dob_controller is a implementation of a disturbance observer based control. It tries to estimate the disturbance and compensate it. This is at a very experimental stage. It works in SITL, but flies a bit aggressively which I am not sure how it would behave on a real drone.

**Comment by Jaeyoung-Lim** [comment] 2019-04-10 08:26
Closing as the issue is resolved

**Closed by Jaeyoung-Lim** 2019-04-10 08:26 UTC
Labels: question
